// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./src/prisma/models",
  migrations: {
    path: "./src/prisma/migrations",
    seed: "ts-node ./src/prisma/seeders/seed.ts"
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});